name: dua_app
description: "Dua social media for muslims"


version: 1.0.0+1

environment:
  sdk: '^3.9.0-333.2.beta'


dependencies:
  flutter:
    sdk: flutter


  package_info_plus: ^8.0.0

  flutter_dotenv: ^5.1.0

  # Networking
  http: ^1.2.0

  flutter_facebook_auth: ^7.0.0


  #Localisations
  flutter_localizations :
    sdk: flutter
  #firebase notifications
  firebase_messaging: ^15.0.1
  flutter_local_notifications: ^17.1.0
  change_app_package_name: ^1.1.0


  firebase_core: ^3.0.0
  firebase_app_check: ^0.3.1+4


  # Storage & Device
  shared_preferences: ^2.2.2
  device_info_plus: ^10.1.0

  # State Management
  provider: ^6.1.1

  # Utilities
  intl: any

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  share_plus: ^12.0.1
  url_launcher: ^6.3.2
  google_sign_in: ^6.2.1
  firebase_analytics: ^11.6.0
  shimmer: ^3.0.0


  # âœ… Added for Prayer Icon
  font_awesome_flutter: ^10.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1 # Check pub.dev for the latest version
  flutter_lints: ^5.0.0


flutter_launcher_icons:
  android: "launcher_icon" # Generates icons for Android
  ios: true                # Generates icons for iOS
  image_path: "assets/icon/app_icon.png" # Path to your icon image
  # adaptive_icon_background: "#ffffff" # Optional: for Android adaptive icons
  # adaptive_icon_foreground: "assets/icon/foreground.png" # Optional


# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - .env